# How to run:
# docker compose -f example.compose.yml run --rm wimi <image to scan> --base <base image> --scan
services:
  wimi:
    image: ghcr.io/willj4945/whats_in_my_image
    build: .        # Build from source (if needed)
    user: "0:0"     # When running as docker, use a root 0:0. For Podman you shouldn't need this directive.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/out:/work
    working_dir: /work
    environment:
      HOME: /tmp
      # following variables are optional and can be provided via `.env` file
      WIMI_SCANNER_PULL: true
      WIMI_SCANNER_MODE:
      WIMI_TRIVY_IMAGE:
      WIMI_GRYPE_IMAGE:
      WIMI_SCANNER_ENV:
      WIMI_SCANNER_TIMEOUT:
      WIMI_SCANNER_MEMORY:
      WIMI_SCANNER_MOUNT:
      WIMI_SCANNER_USER:
      WIMI_CATALOG:
      WIMI_USERNAME:
      WIMI_PASSWORD:
      TRIVY_SKIP_DB_UPDATE:
      GRYPE_DB_CACHE_DIR:
      GRYPE_DB_AUTO_UPDATE: